### ISSUE TITLE
Ability to configure formatting preferences

### ISSUE THREAD

**Issue by consideRatio** [hukkin/mdformat-config#1]
Thank you for your work on mdformat and plugins @hukkinj1!! :heart: :tada:

I'm looking to adopt mdformat as well as this plugin, but the practice across the repository I work is to indent YAML sequences / lists differently than is currently hardcoded in this project.

__My preference__
```python
yaml.preserve_quotes = True
yaml.indent(mapping=2, sequence=4, offset=2)
```

__Current hardcoding__
https://github.com/hukkinj1/mdformat-config/blob/2afc92ce3f93396e1bd5a42395debdf05af6deab/mdformat_config/__init__.py#L21-L29

---

I looked into [ruamel.yaml's documentation](https://yaml.readthedocs.io/) regarding configuring it, and didn't find a simple way to do it without forcing this plugin to expose configuration options to pass onwards =/

I also didn't conclude it would be easy when I inspected [the source code](https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/main.py#l957).

What do you think, would it be in scope of this project to expose some configuration to pass onwards to ruamel.yaml? My experience in general is that its really tiresome to have to do this 1:1 mapping of configuration, because its often no end to the amount of options you end up needing to map, so its nice if it can be done quite generic.

**Comment by hukkin** [comment]
> Thank you for your work on mdformat and plugins

Glad you find it useful :smiling_face_with_three_hearts: 

> What do you think, would it be in scope of this project to expose some configuration to pass onwards to ruamel.yaml?

It could be if there's a good argument for why someone would use the configuration.

> ....its really tiresome to have to do this 1:1 mapping of configuration....

100 % agree. I much prefer a good working default over extensive configuration options.

Which brings me to: maybe the initially picked default was bad and we could simply change it? I have the feeling that indenting lists is much more common than not doing so, e.g. YAML spec examples seem to do so. Seeing that you might well be the first person ever to find and use this plugin, lol, it wouldn't cause much disturbance to change the default to `yaml.indent(mapping=2, sequence=4, offset=2)`

About `yaml.preserve_quotes = True`  ---  is there a good reason you'd want this? Having spent a few hours of my life discussing meaningless "tabs vs spaces" and "single vs double quotes" matters I've come to the conclusion that making an opinionated autoformatter which simply picks one, and sticks to it can be considered a good deed and will save countless hours of other people discussing the same matter.

**Comment by consideRatio** [comment]
> Having spent a few hours of my life discussing meaningless "tabs vs spaces" and "single vs double quotes" matters I've come to the conclusion that making an opinionated autoformatter which simply picks one [...]

I agree with you, and I'm mistaken, I'd like to use double quotes by default and sequence=4/offset=2 indentation ^^

I'd personally be happy with a change to those specifically, I just worry about an arising argument about needing to be able to use different configurations.

I guess in practice, what I'd like most of all, is a plugin exactly like this but would run [prettier](https://prettier.io/). Prettier is the autoformatter we use for our config files that are not nested in markdown code blocks. Prettier can be configured with an external file to override default formatting choices, even though in this specific case, the default is to use the double quotes / sequence indentation.

**Comment by hukkin** [comment]
I changed the indentation style in the latest release. I didn't change the quotation style (currently single quotes) as I don't think either style is better (also too lazy to find out how to change it in `ruamel.yaml` haha).

> I guess in practice, what I'd like most of all, is a plugin exactly like this but would run prettier.

This is VERY easy to implement if you want to do so. You basically
- copy paste the [gofmt plugin](https://github.com/hukkinj1/mdformat-gofmt)
- change [this line](https://github.com/hukkinj1/mdformat-gofmt/blob/83652a651900c6f7697c198e932bb715109bb400/mdformat_gofmt/__init__.py#L9) to `["prettier", "--stdin-filepath", "dummy-name.md"],`. Also make the function name reference markdown
- Fix Go references to Markdown on [this line](https://github.com/hukkinj1/mdformat-gofmt/blob/83652a651900c6f7697c198e932bb715109bb400/pyproject.toml#L30)
- Small maintenance: update the package name, metadata etc.

Note that you can have formatter functions for more than one language in the same plugin, i.e. you can format all languages supported by prettier (JS, TS, HTML etc.).

This sort of plugin runs prettier in a subprocess, so the obvious downside is that it isn't native Python, and prettier will have to be installed in the environment.

**Comment by hukkin** [comment]
Closing, as the indentation style is now changed. Configuration can be rediscussed if someone needs the style where lists are not indented.
